### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by Abhinav7903** [sayakdeepghosh01/Sayak_Ghosh#1]
Hompage contact button not working fix it and fix the contact form.

**Comment by sayakdeepghosh01** [comment]
Thank You for pointing out

**Comment by Abhinav7903** [comment]
Use https://formspree.io/  this for receiving mail in easy way :)

**Comment by sayakdeepghosh01** [comment]
okay Thank You

**Comment by Abhinav7903** [comment]
No problem! :)
